project:
  type: website
author:
  - name: "Dr. CBC Girard"
    # affiliation: "Chapman University - Fowler School of Engineering"
    email: "cgirard@chapman.edu"
    url: "https://cbcgirard.github.io"
website:
  title: "SEA-Arduino"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: intro.qmd
        text: Intro
      - href: lines.qmd
        text: Line following
      - href: ultrasonic.qmd
        text: Obstacle avoidance
      - href: final.qmd
        text: Finale


license: "CC BY-SA"

format:
  chapman-manual-html:
    theme: [chapman.scss]

code-line-numbers: true
code-overflow: wrap


filters:
   - include-code-files
  #  - custom-callouts
   - quarto-header-icon


custom_callouts:
  - name: objective
    icon: clarity:bullseye-line
    heading: "Objective:"
    attr:
      font-size: 1.5em
    color: "#00966C"
  - name: hint
    heading: (hint...)
    icon: bi:hand-index-thumb
    attr:
      flip: vertical
    collapse: true
    color: "#6E6259"
  - name: video
    heading: "Video:"
    icon: bi:camera-video
    collapse: true
    color: "#e67418"
  - name: troubleshooting
    heading: "Troubleshooting"
    attr:
      font-size: 2em
    icon: grommet-icons:troubleshoot
    color: "#68108E"
  - name: example
    color: "#009CA6"
    heading: "Example:"
    icon: lucide:hand-platter
  - name: detail
    collapse: true
    color: "#DDCBA4"
    icon: fontisto:sunglasses
    heading: "also..."
    # yellow: EOB61F



# header_icon:
#   custom_icons:
#     - images/my_icons.json